name: Deploy to Vercel

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: vercel-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    uses: yearn/yearn-gha/.github/workflows/vercel-deploy.yml@711efc3dc97f65bbf6d6045d593732a935171e32
    with:
      vault: webops-prod-yvusd-apr-service
      environment: ${{ github.event_name == 'pull_request' && 'preview' || 'production' }}
      secrets: |
        ETH_RPC_URL=yvusd-apr-service/ETH_RPC_URL
        ARB_RPC_URL=yvusd-apr-service/ARB_RPC_URL
        BASE_RPC_URL=yvusd-apr-service/BASE_RPC_URL
        KAT_RPC_URL=yvusd-apr-service/KAT_RPC_URL
        REDIS_URL=yvusd-apr-service/REDIS_URL
        HYPERSYNC_API_TOKEN=yvusd-apr-service/HYPERSYNC_API_TOKEN
        KONG_WEBHOOK_SECRET=yvusd-apr-service/KONG_WEBHOOK_SECRET
        YVUSD_ADDRESS=yvusd-apr-service/YVUSD_ADDRESS
        LOCKED_YVUSD_ADDRESS=yvusd-apr-service/LOCKED_YVUSD_ADDRESS
        CRON_SECRET=yvusd-apr-service/CRON_SECRET
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
